# This is a basic workflow to help you get started with Actions

name: test

env: 
  PROJECT_NAME:    PointCloudSegmentation
  BUILD_DIR:       docker-env
  DOCKER_REP_NAME: point_cloud_segmentation
on:
  release:
    types: [published]
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Python Pylin GitHub Action
      uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pytest test/unit
